version: '3'
volumes:
  cassandra1:
    driver: local
services:
  couchbase:
    image: couchbase:latest
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "11210:11210"

  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - couchbase
    links:
      - couchbase